title: My Awesome Site
description: A simple personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "Vikash.app" # replace with your actual domain

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

author:
  name: Vikash Kumar
  email: Contact@vikash.app

permalink: pretty
