const galleryData = [
  {
    id: 1,
    src: "/watermarked/Berlin.jpeg",
    alt: "Brandenburg Gate and the vibrant streets of Berlin",
    location: "Berlin, Germany",
    destinationId: 1,
  },
  {
    id: 2,
    src: "/watermarked/prague.jpeg",
    alt: "Gothic spires and red rooftops of Prague's Old Town",
    location: "Prague, Czech Republic",
    destinationId: 2,
  },
  {
    id: 3,
    src: "/watermarked/Vienna.jpeg",
    alt: "Imperial palaces and classical architecture in Vienna",
    location: "Vienna, Austria",
    destinationId: 3,
  },
  {
    id: 4,
    src: "/watermarked/Binz.jpeg",
    alt: "White sandy beach and resort architecture in Binz on Ruegen island",
    location: "Binz, Germany",
    destinationId: 4,
  },
  {
    id: 5,
    src: "/watermarked/Amsterdam.jpeg",
    alt: "Canal houses and bridges along Amsterdam's waterways",
    location: "Amsterdam, Netherlands",
    destinationId: 5,
  },
  {
    id: 6,
    src: "/watermarked/Dresden.jpeg",
    alt: "Baroque skyline of Dresden along the Elbe River",
    location: "Dresden, Germany",
    destinationId: 6,
  },
  {
    id: 7,
    src: "/watermarked/leipzig.jpeg",
    alt: "Historic market square and cultural landmarks of Leipzig",
    location: "Leipzig, Germany",
    destinationId: 7,
  },
  {
    id: 8,
    src: "/watermarked/Venice.jpeg",
    alt: "Gondolas and ornate palaces along Venice's Grand Canal",
    location: "Venice, Italy",
    destinationId: 8,
  },
  {
    id: 9,
    src: "/watermarked/Rome.jpeg",
    alt: "The Colosseum and ancient ruins of Rome at golden hour",
    location: "Rome, Italy",
    destinationId: 9,
  },
  {
    id: 10,
    src: "/watermarked/Naples.jpeg",
    alt: "Bay of Naples with Mount Vesuvius in the background",
    location: "Naples, Italy",
    destinationId: 10,
  },
  {
    id: 11,
    src: "/watermarked/Dublin.JPEG",
    alt: "Colorful Georgian doors and lively streets of Dublin",
    location: "Dublin, Ireland",
    destinationId: 11,
  },
  {
    id: 12,
    src: "/watermarked/Patna.JPEG",
    alt: "Historic Golghar granary and the Ganges riverfront in Patna",
    location: "Patna, India",
    destinationId: 12,
  },
  {
    id: 13,
    src: "/watermarked/Bodhgaya.jpeg",
    alt: "The Mahabodhi Temple and sacred Bodhi Tree in Bodh Gaya",
    location: "Bodh Gaya, India",
    destinationId: 13,
  },
  {
    id: 14,
    src: "/watermarked/Hyd.JPEG",
    alt: "The Charminar monument and bustling bazaars of Hyderabad",
    location: "Hyderabad, India",
    destinationId: 14,
  },
  {
    id: 15,
    src: "/watermarked/Agra.jpeg",
    alt: "The Taj Mahal in white marble against the morning sky",
    location: "Agra, India",
    destinationId: 15,
  },
];

export default galleryData;
