export const TravelDestinations = [
  {
    id: 1,
    title: "Berlin",
    location: "Berlin, DE",
    image: "/assets/cabin.jpg",
    latitude: 52.5200,
    longitude: 13.4050,
    description: "A joyfull City.",
    
  },
  {
    id: 2,
    title: "Prague",
    location: "Prague, CZ",
    image: "/assets/loft.jpg",
    latitude: 50.0755,
    longitude: 14.4378,
    description: "Experience city life.",
  },
  {
    id: 3,
    title: "Vienna",
    location: "Vienna, AT",
    image: "/assets/beach.jpg",
    latitude: 48.2082,
    longitude: 16.3738,
    description: "Enjoyed Historic Destinations.",
  },
   {
    id: 4,
    title: "Binz",
    location: "Binz, DE",
    image: "/assets/beach.jpg",
    latitude: 54.4000,
    longitude: 13.6167,
    description: "Enjoyed Beach and Forest trips.",
  },
 {
    id: 5,
    title: "Amsterdam",
    location: "Amsterdam, NL",
    image: "/assets/beach.jpg",
    latitude: 52.3676,
    longitude: 4.9041,
    description: "Short City trip.",
  },
 {
    id: 6,
    title: "Dresden",
    location: "Dresden, DE",
    image: "/assets/beach.jpg",
    latitude: 51.0504,
    longitude: 13.7373,
    description: "Trip to the city.",
  },
 {
    id: 7,
    title: "Leipzig",
    location: "Leipzig, DE",
    image: "/assets/beach.jpg",
    latitude: 51.3397,
    longitude: 12.3731,
    description: "Trip to the city.",
  },
{
    id: 8,
    title: "Venice",
    location: "Venice, IT",
    image: "/assets/beach.jpg",
    latitude: 45.4408,
    longitude: 12.3155,
    description: "Trip to the city.",
  },
{
    id: 9,
    title: "Rome",
    location: "Rome, IT",
    image: "/assets/beach.jpg",
    latitude: 41.9028,
    longitude: 12.4964,
    description: "Trip to the city.",
  },
{
    id: 10,
    title: "Naples",
    location: "Naples, IT",
    image: "/assets/beach.jpg",
    latitude: 40.8518,
    longitude: 14.2681,
    description: "Trip to the city.",
  },
{
    id: 11,
    title: "Dublin",
    location: "Dublin, IL",
    image: "/assets/beach.jpg",
    latitude: 53.3498,
    longitude: -6.2603,
    description: "Trip to the city.",
  },
{
    id: 12,
    title: "Patna",
    location: "Patna, IN",
    image: "/assets/beach.jpg",
    latitude: 25.5941,
    longitude: 85.1376,
    description: "Trip to the city.",
  },
{
    id: 13,
    title: "BodhGaya",
    location: "BodhGaya, IN",
    image: "/assets/beach.jpg",
    latitude: 24.6950,
    longitude: 84.9914,
    description: "Trip to the city.",
  },
{
    id: 14,
    title: "Hyderabad",
    location: "Hyderabad, IN",
    image: "/assets/beach.jpg",
    latitude: 17.3850,
    longitude: 78.4867,
    description: "Trip to the city.",
  },
{
    id: 15A,
    title: "Agra",
    location: "Agra, IN",
    image: "/assets/beach.jpg",
    latitude: 27.1767,
    longitude: 78.0081,
    description: "Trip to the city.",
  }
];